[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/", 
    "@solmate/=lib/solmate/",
    "@chainlink/contracts/=node_modules/@chainlink/contracts",
    "@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip",
]
gas_reports = ["MakerDAOYieldStrategy", "Vault"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
